version: "3.3"

networks:
  net:
    driver: bridge

services:
  # database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: go-homework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: 'postgres-container'
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - net
  # service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G
    container_name: 'app-container'
    restart: unless-stopped
    hostname: server
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5432/go-homework # должно быть в секретах/конфиге. Учебный пример
    ports:
      - "8080:8080"
      # - 8090:8090
    command: ./app
    depends_on:
      - postgres
    networks:
      - net

